create table if not exists work_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  settings_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table work_profiles enable row level security;

-- 先删除旧策略
drop policy if exists "Users can view own profile" on work_profiles;
drop policy if exists "Users can insert own profile" on work_profiles;
drop policy if exists "Users can update own profile" on work_profiles;

-- 再创建新策略
create policy "Users can view own profile"
on work_profiles
for select
using (auth.uid() = user_id);

create policy "Users can insert own profile"
on work_profiles
for insert
with check (auth.uid() = user_id);

create policy "Users can update own profile"
on work_profiles
for update
using (auth.uid() = user_id);
